# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
     providers:
           my_provider:
             entity:
                 class: AppBundle\Entity\User
                 property: email


     role_hierarchy:
         ROLE_CONTENT_MANAGER: ROLE_USER
         ROLE_ADMIN: ROLE_CONTENT_MANAGER

     encoders:
         AppBundle\Entity\User: bcrypt


     firewalls:
         dev:
             pattern: ^/(_(profiler|wdt)|css|images|js)/
             security: false

         main:
             anonymous: ~
             form_login:
                 login_path: user_login
                 check_path: user_login
                 default_target_path: category
                 always_use_default_target_path: true

             logout:
                 path:   user_logout
                 target: user_login



     access_control:
         - { path: /ajax/ , roles: ROLE_CONTENT_MANAGER }
         - { path: /admin/user , roles: ROLE_ADMIN }
         - { path: /admin , roles: ROLE_CONTENT_MANAGER }
         - { path: /user/edit , roles: ROLE_ADMIN }
         - { path: /news/create , roles: ROLE_CONTENT_MANAGER }
         - { path: /news/edit , roles: ROLE_CONTENT_MANAGER }
         - { path: /category/create , roles: ROLE_CONTENT_MANAGER }
         - { path: /category/edit , roles: ROLE_CONTENT_MANAGER }
         - { path: /login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: /register , roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: /activate , roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: /restore , roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/ , roles: ROLE_USER }