<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Query\ResultSetMapping;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function sendToDataBaste(Category $category)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($category);
        $entityManager->flush();
    }

    public function getCategory(int $name)
    {
        $entityManager = $this->getEntityManager();
        $sql='SELECT news.name,news.description, news.views, news.created_at, news.id  FROM news_category INNER JOIN news WHERE news.id = news_category.news_id AND news_category.category_id = :name';
        $stmt = $entityManager->getConnection()->prepare($sql);
        $stmt->bindValue(':name',$name);
        $stmt->execute();
        $result = $stmt->fetchAll();
        //var_dump($result);



        return $result;
    }


}
