<?php

namespace AppBundle\Entity;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function sendToDataBaste(Category $category)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($category);
        $entityManager->flush();
    }

    public function getCategory(string $name)
    {
        $entityManager = $this->getEntityManager();
        $category = $entityManager->getRepository('AppBundle:Category')->findOneByName($name);
        return $category;
    }
}
