<?php

namespace AppBundle\Entity;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends \Doctrine\ORM\EntityRepository
{
    public function sendToDataBase(Token $token)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($token);
        $entityManager->flush();
    }

    public function activateUserByToken(string $token)
    {
        $entityManager = $this->getEntityManager();
        $fullyToken = $entityManager->
        getRepository('AppBundle:Token')->findOneByToken($token);
        if (isset($fullyToken)) {
            $user = $fullyToken->getUser();
            if ($this->checkToken($fullyToken)) {
                $user->setEnabled(true);
            }
            $entityManager->persist($user);
            $this->removeToken($fullyToken);

        }
    }

    public function removeToken(Token $fullyToken)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->remove($fullyToken);
        $entityManager->flush();
    }

    public function getToken(string $token)
    {
        $entityManager = $this->getEntityManager();
        $fullyToken = $entityManager->
        getRepository('AppBundle:Token')->findOneByToken($token);
        if (isset($fullyToken)) {
            return $fullyToken;
        }
    }

    public function checkToken(Token $fullyToken)
    {
        $diff = date_diff($fullyToken->getDate(), date_create(date('Y-m-d H:i:s')));
        if ($diff->days < 3) {
            return true;
        }
        return false;
    }
}
