<?php

namespace AppBundle\Entity;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends \Doctrine\ORM\EntityRepository
{
    public function sendToDataBase(Token $token)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($token);
        $entityManager->flush();
    }

    public function activateUserByToken(string $token)
    {
        $entityManager = $this->getEntityManager();
        $tokenArray = $entityManager->getRepository('AppBundle:Token')->findByToken($token);
        if(count($tokenArray)!= 0 ){
            $fullyToken = $tokenArray[0];
            $user = $fullyToken->getUser();
            if($this->checkToken($fullyToken)){
                $user->setEnabled(true);
            }
            $entityManager->remove($fullyToken);
            $entityManager->persist($user);
            $entityManager->flush();
        }
    }

    private function checkToken(Token $fullyToken)
    {
        $diff = date_diff($fullyToken->getDate(),date_create(date('Y-m-d H:i:s')));
        if($diff->days < 3){
            return true;
        }
        return false;
    }
}
