<?php

namespace AppBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function sendToDataBase(User $user)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($user);
        $entityManager->flush();
    }

    public function findUserByEmail(string $email)
    {
        $userRepository = $this->getRepository('AppBundle:User');
        $user = $userRepository->findOneByEmail($email);
        return $user;
    }

    public function deleteUserFromDataBase(int $userId)
    {
        $entityManager = $this->getEntityManager();
        $userRepository = $this->getRepository('AppBundle:User');
        $user = $userRepository->findOneById($userId);
        $entityManager->remove($user);
        $entityManager->flush();
    }

    public function getRepository(string $repository)
    {
        $entityManager = $this->getEntityManager();
        return $entityManager->getRepository($repository);
    }


    public function getAllDispatchUsers()
    {
        $userRepository = $this->getRepository('AppBundle:User');
        $users = $userRepository->findBy(['dispatch' => true, 'enabled' => 1]);
        return $users;
    }
}
